name: Build ssh authorized_keys file

on:
  push:
    branches:
      - main
    paths:
      - 'public_keys/*'
      - '.github/workflows/*'
      - 'make_authorized_users.bash'
    tags:
        - 'latest'

defaults:
  run:
    shell: bash

jobs:
  create-authorized-keys:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Run script
        run: bash ./make_authorized_users.bash
        env:
          ENV_AUTH_FILE: ./authorized_keys

      - name: Show Authorized Keys
        run: cat ./authorized_keys

      - name: Remove nightly tag if exists
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            try {
                await github.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: "tags/nightly"
                })
            } catch (e) {
              console.log("The nightly tag doesn't exist yet: " + e)
            }
      
      - name: Add nightly tag
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/nightly",
              sha: context.sha
            })

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/tags/latest'
        with:
          files: ./authorized_keys
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        